services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: Starter
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - starter-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d Starter"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  seq:
    image: datalust/seq:2025.2
    environment:
      ACCEPT_EULA: "Y"
    ports:
      - "5341:5341"
    volumes:
      - starter-seq-data:/data

  keycloak:
    image: ghcr.io/stebzdev/dotnet-api-starter-keycloak:latest
    command: start-dev --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - starter-keycloak-data:/opt/keycloak/data

  starter-migrations:
    image: ghcr.io/stebzdev/dotnet-api-starter-migrations:latest
    environment:
      ConnectionStrings__StarterDb: "Host=postgres;Port=5432;Database=Starter;Username=postgres;Password=postgres"
    depends_on:
      postgres:
        condition: service_healthy

  starter-api:
    image: ghcr.io/stebzdev/dotnet-api-starter-api:latest
    ports:
      - "8081:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development

      ConnectionStrings__StarterDb: "Host=postgres;Port=5432;Database=Starter;Username=postgres;Password=postgres"
      ConnectionStrings__cache: "redis:6379"

      SEQ_URI: "http://seq:5341"

      Keycloak__Realm: Starter
      Keycloak__Audience: Starter-api
      Keycloak__Issuer: "http://localhost:8080/realms/Starter"

      services__keycloak__http__0: "http://keycloak:8080"

    depends_on:
      starter-migrations:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
      keycloak:
        condition: service_started
      seq:
        condition: service_started

volumes:
  starter-postgres-data:
  starter-keycloak-data:
  starter-seq-data: