@Starter.Api_HostAddress = https://localhost:7055

### Create sample items

POST {{Starter.Api_HostAddress}}/api/sample-items
Content-Type: application/json

{
  "name": "Aurora Financial Group",
  "code": "AFG001"
}
