<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NetArchTest.Rules" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Starter.Application\Starter.Application.csproj" />
    <ProjectReference Include="..\..\src\Starter.Api\Starter.Api.csproj" />
    <ProjectReference Include="..\..\src\Starter.Application\Starter.Application.csproj" />
    <ProjectReference Include="..\..\src\Starter.Domain\Starter.Domain.csproj" />
    <ProjectReference Include="..\..\src\Starter.Infrastructure\Starter.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>