// <auto-generated />
using System;
using Starter.Application.Common.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Starter.Application.Migrations
{
    [DbContext(typeof(StarterDbContext))]
    [Migration("20260904133119_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Starter.Domain.ReportingPeriods.ReportingPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("ReferenceMonth")
                        .HasColumnType("integer");

                    b.Property<int>("ReferenceYear")
                        .HasColumnType("integer");

                    b.Property<Guid>("ReportingEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReportingEntityId", "ReferenceYear", "ReferenceMonth")
                        .IsUnique();

                    b.ToTable("reporting_periods", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
