// <auto-generated />
using System;
using System.Collections.Generic;
using Starter.Application.Common.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Starter.Application.Migrations
{
    [DbContext(typeof(StarterDbContext))]
    partial class StarterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Starter.Domain.ReportingEntities.ReportingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("reporting_entities", (string)null);
                });

            modelBuilder.Entity("Starter.Domain.ReportingPeriods.ReportingPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReportingEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ReferencePeriod", "Starter.Domain.ReportingPeriods.ReportingPeriod.ReferencePeriod#ReferencePeriod", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Month")
                                .HasColumnType("integer")
                                .HasColumnName("ReferenceMonth");

                            b1.Property<int>("Year")
                                .HasColumnType("integer")
                                .HasColumnName("ReferenceYear");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ReportingEntityId");

                    b.ToTable("reporting_periods", (string)null);
                });

            modelBuilder.Entity("Starter.Domain.ReportingPeriods.ReportingPeriod", b =>
                {
                    b.HasOne("Starter.Domain.ReportingEntities.ReportingEntity", null)
                        .WithMany()
                        .HasForeignKey("ReportingEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
